variables:
  BUILD_ARTIFACTS:
    value: "false"
    options: [ "false", "true" ]
    description: "Runs _build.command and archives the created ObjectBoxGenerator.artifactbundle.zip"

stages:
  - build

build:
  stage: build
  tags: [mac, arm64, xcode]
  script:
    - swift build
    - swift package plugin --allow-writing-to-package-directory swiftlint
    - swift test

# There is currently no need to always run this as the build job ensures the project can be built and has no errors.
# Also, the Swift library repo currently runs _build.command itself.
build_artifacts:
  stage: build
  needs: [ 'build' ]
  tags: [mac, arm64, xcode]
  rules:
    # Only if explicitly enabled and previous stage did not fail
    - if: $BUILD_ARTIFACTS == "true"
      when: on_success
    # Always build for dev and main branches
    - if: $CI_COMMIT_BRANCH == "dev" || $CI_COMMIT_BRANCH == "main"
      when: on_success
    - when: never # Otherwise, never
  script:
    - ./_build.command
  artifacts:
    when: always
    expire_in: 3 days
    paths:
      - ./bin/ObjectBoxGenerator.artifactbundle.zip
